### PR TITLE
[linz_bde_uploader_private] LOL 3.14 remove meshblock and electoral p…

### PR DESCRIPTION
**Pull request by imincik**
…lace tables and unloads

See: https://github.com/linz/linz_bde_uploader_private/commit/d9a6af07060ca04fef461de70ecedc944a21f6e2

### CODE REVIEW

**Comment by strk** [comment]
I love patches that _drop_ things.
But what about the patches  part, which was in the original commit ?

**Comment by strk** [comment]
It looks like patches in the original commit should be ported to https://github.com/linz/linz-lds-bde-schema ?

**Comment by strk** [comment]
According to CHANGELOG this repository already got changes required for compatibility to LoL 3.15, but this PR mentions 3.14 - was this a left-over ? Shall we report 3.15 compatibility for next release of this package ?

**Comment by strk** [comment]
Please review https://github.com/linz/linz_bde_uploader/blob/master/CHANGELOG.md @billgeo @imincik  - see how Landonline 3.15 is mentioned for release 2.3.0 and we're now doing 3.14 things for 2.4.0...

**Comment by billgeo** [comment]
Hi @strk. That looks okay to me. LOL 3.14 was released July 2016, so an attempt to process BDE files since then should fail in version <2.4.0.

**Pull request merged**
