### PR TITLE
fixes #45 - Landonline 3.15 BDE changes

### LINKED ISSUE #45: Landonline 3.15 BDE changes
From Dec 11 these files will no longer be part of the BDE:

rna
sad1
rcl1 – crs_road_ctr_line
rns - crs_road_name_asc
xrna - crs_road_name
xsad - crs_street_address

### PR DESCRIPTION
**Pull request by billgeo**
@palmerj, can you confirm that this is how to do this?

### CODE REVIEW

**Comment by palmerj** [comment]
This looks good. Did you test it?

**Comment by billgeo** [comment]
How do I test it?

**Comment by palmerj** [comment]
Talk to @imincik, but I think he need to package up for development PPA then rerun the travis test. Once find this out can you document the process on the wiki?

**Comment by billgeo** [comment]
Hi @imincik, can you tell me what I need to do to test so we can get this pull request merged and rolled out to the servers?

**Comment by palmerj** [comment]
Hi @imincik, before you release and package you also need to merge this request as well: https://github.com/linz/linz_bde_uploader/pull/44

**Comment by imincik** [comment]
I tested this path. It is OK.

**Pull request merged**
